# Generated by Django 4.0.3 on 2022-03-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tskDesc',
            new_name='taskDesc',
        ),
    ]
